### ISSUE TITLE
Several Live Demos are missing

### ISSUE THREAD

**Issue by Erudition** [dao-xyz/peerbit-examples#4]
The docs say that "Click here to see live demos" which points to a page listing examples, including:

/one-chat-room/
/many-chat-rooms/

But these example does not appear to have a live demos - they only contain instructions to  manually download, build, and run locally.

This is also the case for the file sharing example, though I guess a live demo wouldn't be practical there because it's a CLI tool.

This is not the case for e.g. the streaming example, which does have a live demo. However, the listed example "Collaborative Machine Learning" actually just links to the simple streaming example, not something with a frontend resembling the demo GIF.

**Comment by marcus-pousette** [comment]
Thanks for creating this issue. 

There are three live demos right now deployed, but only 1 had the actual link available in the README as you have noticed. 

I added all the links just now to respective examples

One chat room
https://chat.dao.xyz   (Create a room in one tab and copy the link and open it in another tab)

ML Demo 
https://mldemo.dao.xyz

Live stream
https://stream.dao.xyz/


The rest of the demos have to clone the repo and run the frontend app locally. 

Working continuously on making the examples better. There will be a release in a few days simplifying some of the example code and adding more examples.

**Comment by Erudition** [comment]
Those work, thanks!
